name: AWS-EC2 Instance CD

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: [completed]

jobs:
  on-success:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          # AWS access key id
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS secret access key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Where EC2 instance is
          aws-region: ${{ secrets.AWS_REGION }}
          # AWS EC2 Instance id or ids
          instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
          # Command execution location
          working-directory: /home/ubuntu
          # Bash commands you want to execute
          command: |
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -af
          # Comment for Send-Command
          comment: docker-compose.yml file re-pulls newer versions of io-project images and runs them on the instance.